name: create-feat-branch
on: 
    label:
        types: [created, edited]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: khfd
          run: echo "${{ Object.keys(github.event.action) }}"
